# Generated by Django 6.1.1 on 2026-10-05 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Building',
            new_name='Book',
        ),
        migrations.RenameModel(
            old_name='Company',
            new_name='Genre',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='company',
            new_name='genre',
        ),
    ]
